[audio]
device = "default"
sample_rate = 16000
block_duration_ms = 30
ring_buffer_duration_s = 6.5
pre_roll_s = 0.85
post_roll_s = 0.20

[model]
path = "models/faster-whisper-base.en/"
compute_type = "int8"
device = "cpu"

# latency/quality
beam_size = 1
repetition_penalty = 1.2
log_prob_threshold = -1.0

# stability & filters
language = "en"
temperature = 0.0
compression_ratio_threshold = 2.4
no_speech_threshold = 0.6
condition_on_previous_text = false
word_timestamps = false

# VAD
vad_min_silence_ms = 300
vad_speech_pad_ms = 30
# vad_threshold = 0.5  # optional

# CPU hints
cpu_threads = 4
num_workers = 1

# Env caps
omp_num_threads = 4
mkl_num_threads = 1
openblas_num_threads = 1

[ui]
hotkeys = ["ctrl_r", "shift_r"]
hotkey_voicenote = ["ctrl_r", "alt_r"]
voicenote_file = "~/ObsidianVault1/🎙️VoiceNotes.md"
enable_audio_cues = true
